Algoritmo "Exercicio5.2"
// Disciplina  :  Lógica de Programação]
// Professor   : Jailson
// Descrição   : Atividade 5 da apostila faccat
// Autor(a)    : João Victor Lima Dos Santos Manço
// Data atual  : 29/08/2025
Var
// Seção de Declarações das variáveis
num1 : inteiro
sucessor : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva ("Escreva um numero: ")
leia (num1)
sucessor <-num1+1
escreva ("O numero seguinte ao ",num1," é: ",sucessor)


Fimalgoritmo